# Etapa 1: build da aplicação
FROM node:18 AS builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

# Etapa 2: Nginx para servir os arquivos
FROM nginx:alpine

# Copia o build do React para o diretório padrão do Nginx
COPY --from=builder /app/build /usr/share/nginx/html

# Copia um arquivo customizado do Nginx (opcional)
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
