# Usar uma imagem base do Node.js
FROM node:16

# Definir diretório de trabalho dentro do container
WORKDIR /app

# Copiar o arquivo package.json e package-lock.json para dentro do container
COPY package*.json ./

# Instalar dependências dentro do container
RUN npm install

# Copiar o restante dos arquivos da aplicação para o diretório do container
COPY . .

# Expor a porta que o servidor vai rodar
EXPOSE 3001

# Comando para rodar a aplicação
CMD ["npm", "start"]
